# Generated by Django 5.2.4 on 2025-08-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'in_store_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('date_received', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_promo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_tbl',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('analgesics', 'Analgesics'), ('antibiotics', 'Antibiotics'), ('antivirals', 'Antivirals'), ('antihypertensives', 'Antihypertensives'), ('antidiabetics', 'Antidiabetics'), ('gastrointestinal_medicines', 'Gastrointestinal Medicines'), ('antihistamines', 'Antihistamines'), ('cough_and_cold_medicines', 'Cough and Cold Medicines'), ('vitamins_and_supplements', 'Vitamins and Supplements'), ('cardiovascular_medicines', 'Cardiovascular Medicines'), ('anti_asthma_and_respiratory_medicines', 'Anti-asthma and Respiratory Medicines'), ('antimalarials', 'Antimalarials'), ('antiparasitics', 'Antiparasitics')], max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50)),
                ('restock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines_list',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('staff', 'Staff')], max_length=20)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.instoreorder')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'in_store_order_items_tbl',
            },
        ),
        migrations.CreateModel(
            name='TotalQuantity',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.medicine')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'total_quantity_tbl',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='accounts.medicine'),
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pickup_schedule', models.DateTimeField(blank=True, null=True)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'db_table': 'online_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.onlineorder')),
            ],
            options={
                'db_table': 'online_order_items_tbl',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'promo_tbl',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('initiate_sale', 'Initiate Sale (In-store)'), ('in_store_approve', 'Approve In-store Order'), ('in_store_reject', 'Reject In-store Order'), ('online_confirmed', 'Online Order Confirmed'), ('online_cancelled', 'Online Order Cancelled'), ('online_picked_up', 'Online Order Picked Up')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.instoreorder')),
                ('online_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.onlineorder')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to='accounts.staff')),
            ],
            options={
                'db_table': 'order_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Add', 'Add'), ('Sold', 'Sold'), ('Restock', 'Restock'), ('Return', 'Return'), ('Delete', 'Delete'), ('Update', 'Update'), ('Promo', 'Promo')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InStoreOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='accounts.instoreorder')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_in_store_orders', to='accounts.staff')),
            ],
            options={
                'db_table': 'in_store_order_approvals_tbl',
            },
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.staff')),
            ],
            options={
                'db_table': 'employee_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'batch_num')},
        ),
    ]
