# Generated by Django 5.2.4 on 2025-07-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'in_store_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('date_received', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_promo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_tbl',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('analgesics', 'Analgesics'), ('antibiotics', 'Antibiotics'), ('antivirals', 'Antivirals'), ('antihypertensives', 'Antihypertensives'), ('antidiabetics', 'Antidiabetics'), ('gastrointestinal_medicines', 'Gastrointestinal Medicines'), ('antihistamines', 'Antihistamines'), ('cough_and_cold_medicines', 'Cough and Cold Medicines'), ('vitamins_and_supplements', 'Vitamins and Supplements'), ('cardiovascular_medicines', 'Cardiovascular Medicines'), ('anti_asthma_and_respiratory_medicines', 'Anti-asthma and Respiratory Medicines'), ('antimalarials', 'Antimalarials'), ('antiparasitics', 'Antiparasitics')], max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50)),
                ('restock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines_list',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('staff', 'Staff')], max_length=20)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.instoreorder')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'in_store_order_items_tbl',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='accounts.medicine'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_free_quantity', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inventory', models.OneToOneField(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'promo_tbl',
            },
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'batch_num')},
        ),
    ]
