# Generated by Django 5.2.4 on 2025-11-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, default='[STAFF NAME]', max_length=255, null=True)),
                ('cashier_name', models.CharField(blank=True, default='[CASHIER NAME]', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_prescription_required_item', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'in_store_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('date_received', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_promo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_tbl',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.CharField(choices=[('analgesics', 'Analgesics'), ('antibiotics', 'Antibiotics'), ('antivirals', 'Antivirals'), ('antihypertensives', 'Antihypertensives'), ('antidiabetics', 'Antidiabetics'), ('gastrointestinal_medicines', 'Gastrointestinal Medicines'), ('antihistamines', 'Antihistamines'), ('cough_and_cold_medicines', 'Cough and Cold Medicines'), ('vitamins_and_supplements', 'Vitamins and Supplements'), ('cardiovascular_medicines', 'Cardiovascular Medicines'), ('anti_asthma_and_respiratory_medicines', 'Anti-asthma and Respiratory Medicines'), ('antimalarials', 'Antimalarials'), ('antiparasitics', 'Antiparasitics')], max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50)),
                ('supplier_name', models.CharField(blank=True, default='[Supplier Deleted]', max_length=255, null=True)),
                ('supplier_contact_num', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('restock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines_list',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(default='System Test User', max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('COMPLETED', 'Completed/Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_request_tbl',
            },
        ),
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Verification Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return_transactions_tbl',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('staff', 'Staff')], max_length=20)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_forecast_report_tbl',
                'unique_together': {('week_start_date',)},
            },
        ),
        migrations.CreateModel(
            name='InStoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.instoreorder')),
                ('inventory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.inventory')),
            ],
            options={
                'db_table': 'in_store_order_items_tbl',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='accounts.medicine'),
        ),
        migrations.CreateModel(
            name='ForecastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('forecasted_quantity', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('restock_amount', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('forecast_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.forecastreport')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicine')),
            ],
            options={
                'db_table': 'demand_forecast_items_tbl',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pickup_schedule', models.DateTimeField(blank=True, null=True)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('initiated_by_name', models.CharField(blank=True, default='[STAFF NAME]', max_length=100, null=True)),
                ('approved_by_name', models.CharField(blank=True, default='[CASHIER NAME]', max_length=100, null=True)),
                ('initiated_by_role_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by_role_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_online_orders', to='accounts.staff')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_online_orders', to='accounts.staff')),
            ],
            options={
                'db_table': 'online_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('medicine_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.onlineorder')),
            ],
            options={
                'db_table': 'online_order_items_tbl',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('in_store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_required', to='accounts.instoreorder')),
                ('online_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_required', to='accounts.onlineorder')),
            ],
            options={
                'db_table': 'prescriptions_tbl',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.prescription')),
            ],
            options={
                'db_table': 'prescription_images_tbl',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'promo_tbl',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_amount', models.IntegerField()),
                ('suggested_amount', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('FORECAST', 'Demand Forecasted'), ('MANUAL', 'Manually Added (New Item)')], default='MANUAL', max_length=10)),
                ('medicine_name_snapshot', models.CharField(max_length=100)),
                ('units_per_item', models.CharField(default='unit', max_length=50)),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_contact_num_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('is_registered_manual_item', models.BooleanField(default=False, help_text='Flag for manually added items that have completed registration.')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.medicine')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_request_item_tbl',
            },
        ),
        migrations.CreateModel(
            name='ReturnedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_num', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicine')),
                ('online_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.onlineorderitem')),
                ('return_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='accounts.returntransaction')),
            ],
            options={
                'db_table': 'returned_medicines_tbl',
            },
        ),
        migrations.CreateModel(
            name='ReturnVerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_verification_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_images', to='accounts.returntransaction')),
            ],
            options={
                'db_table': 'return_verification_images_tbl',
            },
        ),
        migrations.AddField(
            model_name='returntransaction',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transactions', to='accounts.staff'),
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('initiate_sale', 'Initiate Sale (In-store)'), ('in_store_approve', 'Approve In-store Order'), ('in_store_reject', 'Reject In-store Order'), ('online_confirmed', 'Online Order Confirmed'), ('online_cancelled', 'Online Order Cancelled'), ('online_picked_up', 'Online Order Picked Up')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.instoreorder')),
                ('online_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.onlineorder')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to='accounts.staff')),
            ],
            options={
                'db_table': 'order_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='[Deleted Staff]', max_length=100)),
                ('staff_role', models.CharField(default='[Deleted Role]', max_length=20)),
                ('medicine_name_log', models.CharField(default='[Unknown]', max_length=100)),
                ('action_type', models.CharField(choices=[('Add', 'Add'), ('Sold', 'Sold'), ('Restock', 'Restock'), ('Return', 'Return'), ('Delete', 'Delete'), ('Update', 'Update'), ('Promo', 'Promo')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff_name', models.CharField(blank=True, default='[Deleted Staff]', max_length=255, null=True)),
                ('staff_role', models.CharField(blank=True, default='[Deleted Role]', max_length=50, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.staff')),
            ],
            options={
                'db_table': 'employee_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='accounts.staff')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier'),
        ),
        migrations.CreateModel(
            name='TotalQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_quantity_entry', to='accounts.medicine', unique=True)),
            ],
            options={
                'db_table': 'total_quantity_tbl',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'batch_num')},
        ),
    ]
