# Generated by Django 5.2.4 on 2025-07-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalQuantity',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.medicine')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'total_quantity_tbl',
            },
        ),
    ]
