# Generated by Django 5.2.4 on 2025-11-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='source',
            field=models.CharField(choices=[('FORECAST', 'Demand Forecasted'), ('MANUAL', 'Manually Added (New Item)')], default='MANUAL', max_length=10),
        ),
    ]
