# Generated by Django 5.2.4 on 2025-09-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instoreorder',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to='accounts.staff'),
        ),
        migrations.DeleteModel(
            name='InStoreOrderApproval',
        ),
    ]
