# Generated by Django 5.2.4 on 2025-11-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='supplier_contact_num_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='supplier_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='units_per_item',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='suggested_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
