# Generated by Django 5.2.4 on 2025-08-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='online_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.onlineorder'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action_type',
            field=models.CharField(choices=[('initiate_sale', 'Initiate Sale (In-store)'), ('in_store_approve', 'Approve In-store Order'), ('in_store_reject', 'Reject In-store Order'), ('online_confirmed', 'Online Order Confirmed'), ('online_cancelled', 'Online Order Cancelled'), ('online_picked_up', 'Online Order Picked Up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='in_store_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.instoreorder'),
        ),
    ]
