# Generated by Django 5.2.4 on 2025-10-31 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='accounts.staff')),
            ],
            options={
                'db_table': 'purchase_request_tbl',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_amount', models.IntegerField()),
                ('suggested_amount', models.IntegerField()),
                ('medicine_name_snapshot', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.medicine')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_request_item_tbl',
            },
        ),
    ]
