# Generated by Django 5.2.4 on 2025-09-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorderitem',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_store_order_items', to='accounts.inventory'),
        ),
        migrations.AlterField(
            model_name='onlineorderitem',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order_items', to='accounts.inventory'),
        ),
    ]
