# Generated by Django 5.2.4 on 2025-08-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'promo_tbl',
            },
        ),
    ]
