# Generated by Django 5.2.4 on 2025-08-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='pickup_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
