# Generated by Django 5.2.4 on 2025-07-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'batch_num')},
        ),
    ]
