# Generated by Django 5.2.4 on 2025-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instoreorder',
            name='cashier_name',
            field=models.CharField(blank=True, default='[CASHIER NAME]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='staff_name',
            field=models.CharField(blank=True, default='[STAFF NAME]', max_length=255, null=True),
        ),
    ]
