# Generated by Django 5.2.4 on 2025-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchaserequestitem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='is_registered_manual_item',
            field=models.BooleanField(default=False, help_text='Flag for manually added items that have completed registration.'),
        ),
    ]
