# Generated by Django 5.2.4 on 2025-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='approved_by_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='initiated_by_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
