# Generated by Django 5.2.4 on 2025-10-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchaserequest_purchaserequestitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequestitem',
            old_name='purchase_request',
            new_name='purchase_request_id',
        ),
    ]
