# Generated by Django 5.2.4 on 2025-07-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoproduct',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_entries', to='accounts.inventory'),
        ),
    ]
