# Generated by Django 5.2.4 on 2025-09-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forecast',
            table='demand_forecast_tbl',
        ),
    ]
