# Generated by Django 5.2.4 on 2025-11-30 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.medicine'),
        ),
    ]
