# Generated by Django 5.2.4 on 2025-08-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prescription_prescriptionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionimage',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionImage',
        ),
    ]
