# Generated by Django 5.2.4 on 2025-08-02 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inventory_is_promo_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Add', 'Add'), ('Sold', 'Sold'), ('Restock', 'Restock'), ('Return', 'Return'), ('Delete', 'Delete'), ('Update', 'Update'), ('Promo', 'Promo')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
