# Generated by Django 5.2.4 on 2025-08-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='in_store_order',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='online_order',
        ),
    ]
