# Generated by Django 5.2.4 on 2025-08-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instoreorder',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='instoreorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
