# Generated by Django 5.2.4 on 2025-09-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instoreorderitem_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='instoreorderitem',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.inventory'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onlineorderitem',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.inventory'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
