# Generated by Django 5.2.4 on 2025-11-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchaserequestitem_supplier_contact_num_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
