# Generated by Django 5.2.4 on 2025-09-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='medicine_name_log',
            field=models.CharField(default='[Unknown]', max_length=100),
        ),
    ]
