# Generated by Django 5.2.4 on 2025-08-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_prescription_in_store_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_store_order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_required_item', to='accounts.instoreorderitem')),
                ('online_order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_required_item', to='accounts.onlineorderitem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='accounts.prescription')),
            ],
            options={
                'db_table': 'prescription_required_items_tbl',
            },
        ),
    ]
