# Generated by Django 5.2.4 on 2025-10-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_purchase_request_purchaserequestitem_purchase_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequestitem',
            old_name='purchase_request_id',
            new_name='purchase_request',
        ),
    ]
