# Generated by Django 5.2.4 on 2025-09-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_forecast_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_forecast_report_tbl',
                'unique_together': {('week_start_date',)},
            },
        ),
        migrations.CreateModel(
            name='ForecastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_quantity', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicine')),
                ('forecast_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.forecastreport')),
            ],
            options={
                'db_table': 'demand_forecast_items_tbl',
            },
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
