# Generated by Django 5.2.4 on 2025-11-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_purchaserequestitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='price',
        ),
    ]
