# Generated by Django 5.2.4 on 2025-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='staff_name',
            field=models.CharField(default='[Deleted Staff]', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='staff_role',
            field=models.CharField(default='[Deleted Role]', max_length=20),
        ),
    ]
