# Generated by Django 5.2.4 on 2025-07-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promoproduct_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoProduct',
        ),
    ]
