# Generated by Django 5.2.4 on 2025-08-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_instoreorder_is_completed_instoreorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('initiate_sale', 'Initiate Sale (In-store)'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_store_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.instoreorder')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to='accounts.staff')),
            ],
            options={
                'db_table': 'order_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
