# Generated by Django 5.2.4 on 2025-10-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastitem',
            name='accuracy_metric',
        ),
        migrations.AddField(
            model_name='forecastitem',
            name='smape_accuracy_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='sMAPE (%)'),
        ),
    ]
