# Generated by Django 5.2.4 on 2025-07-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_testtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirationlist',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='expirationlist',
            table='inventory_tbl',
        ),
    ]
