# Generated by Django 5.2.4 on 2025-10-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedmedicine',
            name='returned_by',
        ),
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Verification Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transactions', to='accounts.staff')),
            ],
            options={
                'db_table': 'return_transactions_tbl',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.AddField(
            model_name='returnedmedicine',
            name='return_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='accounts.returntransaction'),
        ),
        migrations.CreateModel(
            name='ReturnVerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_verification_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_images', to='accounts.returntransaction')),
            ],
            options={
                'db_table': 'return_verification_images_tbl',
            },
        ),
    ]
