# Generated by Django 5.2.4 on 2025-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_promoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
