# Generated by Django 5.2.4 on 2025-11-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_purchaserequestitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
