# Generated by Django 5.2.4 on 2025-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_purchase_request_id_purchaserequestitem_purchase_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='manager',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='manager_name',
            field=models.CharField(default='System Test User', max_length=100),
        ),
    ]
