# Generated by Django 5.2.4 on 2025-07-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('analgesics', 'Analgesics'), ('antibiotics', 'Antibiotics'), ('antivirals', 'Antivirals'), ('antihypertensives', 'Antihypertensives'), ('antidiabetics', 'Antidiabetics'), ('gastrointestinal_medicines', 'Gastrointestinal Medicines'), ('antihistamines', 'Antihistamines'), ('cough_and_cold_medicines', 'Cough and Cold Medicines'), ('vitamins_and_supplements', 'Vitamins and Supplements'), ('cardiovascular_medicines', 'Cardiovascular Medicines'), ('anti_asthma_and_respiratory_medicines', 'Anti-asthma and Respiratory Medicines'), ('antimalarials', 'Antimalarials'), ('antiparasitics', 'Antiparasitics')], max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50)),
                ('restock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier')),
            ],
            options={
                'db_table': 'medicines_list',
            },
        ),
    ]
