# Generated by Django 5.2.4 on 2025-08-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_orderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStoreOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_in_store_orders', to='accounts.staff')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='accounts.instoreorder')),
            ],
            options={
                'db_table': 'in_store_order_approvals_tbl',
            },
        ),
    ]
