# Generated by Django 5.2.4 on 2025-08-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prescriptionrequireditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionrequireditem',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequireditem',
            name='in_store_order_item',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequireditem',
            name='online_order_item',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionRequiredItem',
        ),
    ]
