# Generated by Django 5.2.4 on 2025-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_forecastreport_forecastitem_delete_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastitem',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecastitem',
            name='restock_amount',
            field=models.IntegerField(default=0),
        ),
    ]
