# Generated by Django 5.2.4 on 2025-10-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_returnedmedicine_returned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedmedicine',
            name='medicine_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returntransaction',
            name='staff_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='returnedmedicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicine'),
        ),
    ]
