# Generated by Django 5.2.4 on 2025-09-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inventorylog_staff_name_inventorylog_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelog',
            name='staff_name',
            field=models.CharField(blank=True, default='[Deleted Staff]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='staff_role',
            field=models.CharField(blank=True, default='[Deleted Role]', max_length=50, null=True),
        ),
    ]
