# Generated by Django 5.2.4 on 2025-10-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
