# Generated by Django 5.2.4 on 2025-07-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_inventory_is_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('is_pwd', models.BooleanField(default=False)),
                ('total_amount_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff')),
            ],
            options={
                'db_table': 'in_store_orders_tbl',
            },
        ),
        migrations.CreateModel(
            name='InStoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('free_quantity_given', models.PositiveIntegerField(default=0)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.instoreorder')),
            ],
            options={
                'db_table': 'in_store_order_items_tbl',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_free_quantity', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
            options={
                'db_table': 'promo_tbl',
            },
        ),
    ]
