# Generated by Django 5.2.4 on 2025-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeelog_staff_name_employeelog_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier_name_snapshot',
            field=models.CharField(blank=True, default='[Supplier Deleted]', max_length=255, null=True),
        ),
    ]
