# Generated by Django 5.2.4 on 2025-10-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_returnedmedicine_medicine_name_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnedmedicine',
            old_name='medicine_name_snapshot',
            new_name='medicine_name',
        ),
        migrations.RenameField(
            model_name='returntransaction',
            old_name='staff_name_snapshot',
            new_name='staff_name',
        ),
    ]
