# Generated by Django 5.2.4 on 2025-07-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expirations', to='accounts.medicine')),
            ],
            options={
                'db_table': 'expiration_list',
                'ordering': ['expiration_date'],
            },
        ),
    ]
