# Generated by Django 5.2.4 on 2025-10-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_medicine_name_snapshot_returnedmedicine_medicine_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnedmedicine',
            old_name='medicine_name',
            new_name='generic_name_snapshot',
        ),
        migrations.AddField(
            model_name='returnedmedicine',
            name='medicine_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnedmedicine',
            name='supplier_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
