# Generated by Django 5.2.4 on 2025-10-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medicine_supplier_name_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='supplier_name_snapshot',
            new_name='supplier_name',
        ),
    ]
