# Generated by Django 5.2.4 on 2025-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_supplier_name_snapshot_medicine_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
