# Generated by Django 5.2.4 on 2025-10-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_medicine_name_returnedmedicine_generic_name_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntransaction',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='returntransaction',
            name='staff_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
