# Generated by Django 5.2.4 on 2025-08-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('in_store_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_required', to='accounts.instoreorder')),
            ],
            options={
                'db_table': 'prescriptions_tbl',
            },
        ),
    ]
