# Generated by Django 5.2.4 on 2025-10-04 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_online_orders', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='approved_by_name',
            field=models.CharField(blank=True, default='[CASHIER NAME]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='approved_by_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_online_orders', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='initiated_by_name',
            field=models.CharField(blank=True, default='[STAFF NAME]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='initiated_by_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
