# Generated by Django 5.2.4 on 2025-08-18 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='online_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_required', to='accounts.onlineorder'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='in_store_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_required', to='accounts.instoreorder'),
        ),
    ]
