# Generated by Django 5.2.4 on 2025-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier_contact_num',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
    ]
