# Generated by Django 5.2.4 on 2025-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_returntransaction_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
