# Generated by Django 5.2.4 on 2025-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_instoreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
