# Generated by Django 5.2.4 on 2025-08-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_prescription_online_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_image',
        ),
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.prescription')),
            ],
            options={
                'db_table': 'prescription_images_tbl',
            },
        ),
    ]
