# Generated by Django 5.2.4 on 2025-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_onlineorder_approved_by_onlineorder_approved_by_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
