# Generated by Django 5.2.4 on 2025-10-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_forecastitem_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instoreorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
